# SPDX-License-Identifier: LGPL-2.1-or-later

[Content]
InitrdPackages=
        libfdisk

RemoveFiles=/usr/lib/systemd/network/89-ethernet.network

KernelCommandLine=plymouth.use-simpledrm splash
KernelInitrdModules=/drivers/gpu/drm
InitrdProfiles=plymouth

Splash=/usr/share/pixmaps/fedora-logo.png

Packages=
        bluez
        bolt
        desktop-file-utils
        pax-utils
        pgpdump
        pipewire
        pipewire-alsa
        qemu-guest-agent
        wireless-regdb
        xdg-desktop-portal

        gnome-backgrounds
        gnome-color-manager
        gnome-console
        gnome-control-center
        gnome-disk-utility
        gnome-keyring
        gnome-menus
        gnome-session
        gnome-settings-daemon
        gnome-shell
        gnome-software
        gnome-system-monitor
        gnome-tour
        ibus
        nautilus
        tecla
        xdg-desktop-portal-gnome
        xdg-desktop-portal-gtk
        xdg-user-dirs-gtk

        bash-color-prompt
        bpftool
        cryptsetup
        distribution-gpg-keys
        dnf5
        fedora-release
        fido2-tools
        git-core
        hostname
        integritysetup
        iproute
        iproute-tc
        iputils
        kernel-core
        libcap-ng-utils
        libfido2
        man-db
        man-pages
        openssh
        openssh-clients
        openssh-server
        pam
        passwd
        pcsc-lite
        pcsc-lite-ccid
        perf
        polkit
        procps-ng
        python3
        rpm
        systemd-boot
        systemd-container
        systemd-networkd
        systemd-networkd-defaults
        systemd-oomd-defaults
        systemd-pam
        systemd-resolved
        systemd-ukify
        tpm2-tools
        tpm2-tss
        veritysetup
        vim-minimal
        wget2
        xz
        zram-generator-defaults

        adobe-source-code-pro-fonts
        alsa-sof-firmware
        amd-gpu-firmware
        default-fonts-cjk
        default-fonts-core
        default-fonts-other
        fedora-logos
        glibc-all-langpacks
        glx-utils
        iwlwifi-mvm-firmware
        kernel-modules
        kernel-modules-extra
        linux-firmware
        mesa-dri-drivers
        mesa-vulkan-drivers
        mt7xxx-firmware
        ModemManager
        NetworkManager
        NetworkManager-wifi
        nvidia-gpu-firmware
        pipewire-pulseaudio
        steam-devices
        tuned-ppd
        wpa_supplicant

        adwaita-fonts-all
        gdm
        pinentry-gnome3
        rsms-inter-fonts
        rsms-inter-vf-fonts

        microcode_ctl
        amd-ucode-firmware
        cirrus-audio-firmware
        intel-audio-firmware
        intel-gpu-firmware

VolatilePackages=
        systemd-boot
        systemd-container
        systemd-networkd
        systemd-networkd-defaults
        systemd-oomd-defaults
        systemd-pam
        systemd-resolved
        systemd-ukify
